# Generated by Django 4.1 on 2024-05-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="members",
        ),
    ]
